
import React, { createContext, useContext, useState, useEffect, useCallback, useMemo, ReactNode } from 'react';
import { Translations } from '../types';

type Direction = 'rtl' | 'ltr';
type Language = 'en' | 'he';

interface LocalizationContextType {
    language: Language;
    dir: Direction;
    t: (key: string) => string;
    toggleLanguage: () => void;
    isDarkMode: boolean;
    toggleTheme: () => void;
}

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

const translations: Translations = {
    en: {
        app_title: 'Carpool Yokneam-Binyamina',
        hero_subtitle: 'The smart way to commute between Yokneam and Binyamina.',
        install_title: 'Install App',
        install_subtitle: 'Install the app for a better experience.',
        confirm: 'Got it',
        btn_select_time: 'Select Time',
        btn_select_date: 'Select Date',
        back_home: 'Back Home',
        'Yokneam -> Binyamina': 'Yokneam → Binyamina',
        'Binyamina -> Yokneam': 'Binyamina → Yokneam',
        notif_passenger_left_title: 'Passenger Left',
        notif_passenger_left_msg: '{name} has left your ride.',
        pickup_modal_title: 'Where from?',
        pickup_modal_desc: 'Please enter your pickup location for the driver.',
        pickup_modal_placeholder: 'Example: Near the Big junction...',
        pickup_modal_btn: 'Send Join Request',
        offer_to_join: 'Offer to join',
        invite_to_ride: 'Invite to your ride',
        select_trip_to_invite: 'Select one of your rides:',
        no_active_rides_to_invite: 'No active rides to offer',
        passenger_busy_error: 'Passenger already booked',
        request_status_title: 'Your Request Status',
        share_trip: 'Share',
        share_message_offer: 'Hi! I am driving {direction} on {date} at {time}. Join me: {link}',
        share_message_request: 'Hi! I am looking for a ride {direction} on {date} at {time}. Anyone going? {link}'
    },
    he: {
        app_title: 'קארפול יקנעם-בנימינה',
        hero_subtitle: 'הדרך החכמה והקהילתית להתנייד בין יקנעם לבנימינה.',
        login_subtitle: 'התחברו לקהילת הקארפול שלנו',
        email_address: 'כתובת אימייל',
        password: 'סיסמה',
        remember_me: 'זכור אותי',
        forgot_password: 'שכחת סיסמה?',
        sign_in: 'התחברות',
        or_continue_with: 'או המשיכו עם',
        login_with_google: 'התחברות עם Google',
        dont_have_account: 'אין לך חשבון?',
        sign_up: 'הרשמה',
        create_account: 'יצירת חשבון',
        register_subtitle: 'הצטרפו לקהילת הקארפול',
        full_name: 'שם מלא',
        full_name_en: 'שם מלא באנגלית',
        phone_number: 'מספר טלפון',
        already_have_account: 'כבר יש לך חשבון?',
        reset_your_password: 'איפוס סיסמה',
        forgot_password_subtitle: 'הזינו אימייל לקבלת קישור לאיפוס',
        send_reset_link: 'שלח קישור לאיפוס',
        back_to_login: 'חזרה להתחברות',
        reset_success: 'קישור לאיפוס נשלח בהצלחה!',
        menu_home: 'דף הבית',
        menu_schedule: 'לוח נסיעות',
        menu_profile: 'הפרופיל שלי',
        menu_settings: 'הגדרות',
        menu_about: 'אודות האפליקציה',
        menu_admin: 'ניהול מערכת',
        menu_install: 'התקנת אפליקציה',
        logout: 'התנתקות',
        report_issue: 'דיווח על תקלה',
        yokneam_to_binyamina: 'יקנעם ← בנימינה',
        binyamina_to_yokneam: 'בנימינה ← יקנעם',
        'Yokneam -> Binyamina': 'יקנעם ← בנימינה',
        'Binyamina -> Yokneam': 'בנימינה ← יקנעם',
        tab_offers: 'נהגים',
        tab_requests: 'נוסעים',
        day_all: 'הכל',
        day_today: 'היום',
        day_tomorrow: 'מחר',
        day_upcoming: 'בהמשך',
        no_trips_title: 'אין נסיעות כרגע',
        no_trips_subtitle: 'היו הראשונים להציע נסיעה במסלול זה!',
        no_requests_title: 'אין בקשות כרגע',
        no_requests_subtitle: 'צריכים נסיעה? פרסמו בקשה עכשיו.',
        no_trips_schedule: 'אין נסיעות מתוכננות ליום זה',
        be_the_first: 'פרסם נסיעה',
        post_request_now: 'פרסם בקשה',
        departure_time: 'שעת יציאה',
        departure_date: 'תאריך',
        departure_point_offer: 'נקודת יציאה',
        departure_point_request: 'נקודת איסוף מבוקשת',
        available_seats: 'מקומות פנויים',
        seats_needed: 'מקומות דרושים',
        seats_left: 'מקומות נותרו',
        join: 'בקשת הצטרפות',
        join_pending: 'ממתין לאישור',
        join_approved: 'מאושר/ת',
        me: 'אני',
        trip_type_offer: 'נהג/ת',
        trip_type_request: 'נוסע/ת',
        ride_closed: 'נסיעה סגורה',
        trip_full: 'נסיעה מלאה',
        close_ride: 'סגירת נסיעה',
        open_ride: 'פתיחת נסיעה',
        delete: 'מחיקה',
        confirm: 'הבנתי',
        btn_select_time: 'בחר שעה',
        btn_select_date: 'בחר תאריך',
        cancel: 'ביטול',
        save_changes: 'שמירת שינויים',
        publish_trip: 'פרסם נסיעה',
        publish_request: 'פרסם בקשה',
        post_a_trip: 'הוספת נסיעה',
        edit: 'עריכה',
        call: 'התקשר',
        chat_title: 'צ׳אט נסיעה',
        chat_placeholder: 'הקלדת הודעה...',
        is_typing: '{name} מקליד/ה...',
        no_messages: 'אין הודעות עדיין. תהיו הראשונים לכתוב!',
        location_shared: 'מיקום שותף',
        take_photo: 'צלם תמונה',
        history_title: 'היסטוריית נסיעות',
        history_tab_driver: 'כנהג/ת',
        history_tab_passenger: 'כנוסע/ת',
        history_empty: 'אין נסיעות להצגה בהיסטוריה',
        stats_rides_given: 'נסיעות שנתת',
        stats_trips_taken: 'נסיעות שלקחת',
        profile_edit: 'עריכת פרופיל',
        profile_save: 'שמור שינויים',
        profile_cancel: 'ביטול',
        settings_title: 'הגדרות',
        settings_notifications: 'התראות',
        settings_notifications_desc: 'עדכונים על התאמות והודעות',
        settings_privacy: 'נראות פרופיל',
        settings_privacy_public: 'פרופיל ציבורי',
        settings_privacy_private: 'פרופיל פרטי',
        settings_theme: 'מצב תצוגה',
        settings_theme_dark: 'מצב כהה',
        settings_theme_light: 'מצב בהיר',
        settings_language: 'שפת אפליקציה',
        my_car_title: 'פרטי הרכב שלי',
        car_model: 'דגם הרכב',
        car_color: 'צבע הרכב',
        car_plate: 'מספר רכב',
        car_model_placeholder: 'למשל: מאזדה 3',
        car_color_placeholder: 'למשל: לבן פנינה',
        car_plate_placeholder: 'מספר לוחית רישוי',
        manage_car_details: 'נהלו את פרטי הרכב שלכם',
        admin_panel: 'ניהול מערכת',
        admin_tab_dashboard: 'דשבורד',
        admin_tab_users: 'משתמשים',
        admin_tab_trips: 'נסיעות',
        admin_tab_reports: 'דיווחים',
        admin_tab_broadcast: 'שידור הודעה',
        admin_tab_versions: 'גרסאות',
        admin_health_title: 'סטטוס שירותים',
        admin_stats_title: 'מדדים וסטטיסטיקה',
        admin_broadcast_title: 'שידור הודעה גלובלית',
        admin_broadcast_desc: 'הודעה זו תופיע כמודל קופץ לכל המשתמשים.',
        admin_broadcast_success: 'הודעה שודרה בהצלחה לכולם!',
        admin_broadcast_preview: 'תצוגה מקדימה',
        admin_update_title: 'עדכון מערכת',
        admin_stat_users: 'משתמשים',
        admin_stat_active: 'נסיעות פעילות',
        admin_stat_reports: 'דיווחים פתוחים',
        admin_stat_messages: 'הודעות צ\'אט',
        admin_status_operational: 'תקין',
        admin_status_active: 'פעיל',
        admin_status_optimal: 'אופטימלי',
        status_active: 'פעיל',
        filter_status_all: 'הכל',
        filter_status_active: 'פעילות',
        filter_status_closed: 'סגורות',
        filter_direction_all: 'כל הכיוונים',
        sort_newest: 'מהחדש לישן',
        sort_oldest: 'מהישן לחדש',
        cancel_trip_confirm: 'האם אתם בטוחים שברצונכם למחוק את הנסיעה?',
        confirm_delete_user_admin: 'האם למחוק את המשתמש מהמערכת לצמיתות?',
        confirm_delete_user_msg: 'האם אתם בטוחים שברצונכם למחוק את המשתמש {name} לצמיתות מהמערכת?',
        confirm_delete_trip_msg: 'האם אתם בטוחים שברצונכם למחוק את הנסיעה של {name} בתאריך {date}?',
        error_generic: 'משהו השתבש, נסו שוב מאוחר יותר',
        error_location_required: 'חובה לציין נקודת יציאה',
        install_title: 'התקנת אפליקציה',
        install_subtitle: 'התקינו את האפליקציה לחוויה מלאה הכוללת התראות Push בזמן אמת וגישה מהירה מהמסך הראשי.',
        install_refresh_btn: 'רענן דף',
        install_android_btn: 'התקן עכשיו',
        
        install_ios_header: 'התקנה ב-iPhone (iOS)',
        install_ios_step1: 'לחצו על כפתור ה"שתף" (אייקון של מרובע עם חץ למעלה) בתחתית הדפדפן.',
        install_ios_step2: 'גללו מעט מטה בתפריט שנפתח וחפשו את האפשרות "הוספה למסך הבית" (Add to Home Screen).',
        install_ios_step3: 'לחצו על "הוסף" (Add) בפינה העליונה לאישור. האייקון יופיע במסך הבית שלכם.',
        
        install_android_header: 'התקנה ב-Android',
        install_android_step1: 'לחצו על תפריט שלוש הנקודות (⋮) בפינה העליונה של דפדפן Chrome.',
        install_android_step2: 'חפשו ובחרו באפשרות "התקן אפליקציה" או "הוסף למסך הבית".',
        install_android_step3: 'אשרו את הפעולה בחלונית שתקפוץ. האפליקציה תותקן במכשירכם.',
        
        install_pc_header: 'התקנה במחשב (Desktop)',
        install_pc_chrome_title: 'Google Chrome',
        install_pc_chrome_step: 'לחצו על סמל המחשב עם החץ (Install) שמופיע בשורת הכתובת בצד ימין/שמאל.',
        install_pc_edge_title: 'Microsoft Edge',
        install_pc_edge_step: 'לחצו על סמל הריבועים עם הפלוס (App available) המופיע בשורת הכתובת למעלה.',
        install_pc_firefox_title: 'Firefox',
        install_pc_firefox_step: 'פיירפוקס לא תומך רשמית בהתקנת PWA. מומלץ להשתמש ב-Chrome או ב-Edge.',
        install_pc_generic_step: 'ניתן גם ללחוץ על תפריט הדפדפן (3 נקודות/קווים) ולבחור "התקן אפליקציה".',

        report_modal_title: 'דיווח על תקלה / משוב',
        report_submit: 'שלח דיווח',
        report_submitted: 'תודה רבה! הדיווח התקבל.',
        report_type_bug: 'תקלה',
        report_type_improvement: 'הצעה לשיפור',
        report_desc_placeholder: 'תארו את הבעיה או ההצעה שלכם...',
        about_title: 'קארפול יקנעם-בנימינה',
        about_mission_desc: 'מחברים בין אנשים, חוסכים בעלויות ושומרים על הסביבה.',
        about_stats_title: 'הקהילה שלנו במספרים',
        stat_members: 'חברים רשומים',
        stat_rides: 'נסיעות שפורסמו',
        stat_co2: 'ק"ג CO2 שנחסכו',
        about_how_it_works: 'איך זה עובד?',
        about_step_1_title: 'נרשמים',
        about_step_1_desc: 'יוצרים פרופיל מהיר עם טלפון מאומת.',
        about_step_2_title: 'מחפשים או מציעים',
        about_step_2_desc: 'מוצאים נסיעה קיימת או מפרסמים הצעה משלכם.',
        about_step_3_title: 'נוסעים ביחד',
        about_step_3_desc: 'מתאמים דרך הצ׳אט, אוספים ויוצאים לדרך.',
        about_contact_title: 'זקוקים לעזרה?',
        about_contact_desc: 'צוות התמיכה שלנו זמין לכל שאלה או הצעה לשיפור.',
        contact_via_whatsapp: 'דברו איתנו בוואטסאפ',
        select_time: 'בחירת שעה',
        select_date: 'בחירת תאריך',
        hour: 'שעה',
        minute: 'דקה',
        day: 'יום',
        month: 'חודש',
        year: 'שנה',
        passengers_title: 'נוסעים מאושרים',
        from: 'מ-',
        to: 'ל-',
        city_yokneam: 'יקנעם',
        city_binyamina: 'בנימינה',
        loc_big_yokneam: 'ביג יקנעם',
        loc_g_center: 'מרכז G יקנעם',
        loc_hitech_park: 'פארק הייטק',
        loc_megiddo_junction: 'צומת מגידו',
        loc_elyst_junction: 'צומת אליקים',
        loc_train_binyamina: 'תחנת רכבת בנימינה',
        loc_binyamina_carpool: 'חניון קארפול בנימינה',
        loc_binyamina_ind: 'אזור תעשייה בנימינה',
        loc_custom: 'אחר (הקלדה חופשית)',
        select_common_location: 'בחרו נקודה נפוצה',
        pickup_placeholder_driver: 'מאיפה אתם יוצאים?',
        pickup_placeholder_passenger: 'איפה הכי נוח לכם שיאספו אתכם?',
        back_home: 'חזרה לבית',
        notifications_title: 'התראות',
        no_notifications: 'אין התראות חדשות',
        mark_all_read: 'סמן הכל כנקרא',
        approve: 'אישור',
        reject: 'דחייה',
        badge_newcomer: 'מצטרף חדש',
        badge_frequent_flyer: 'נוסע מתמיד',
        badge_driver_pro: 'נהג מקצוען',
        badge_community_legend: 'אגדה בקהילה',
        terms_title: 'תנאי שימוש',
        terms_subtitle: 'מידע משפטי ופרטיות',
        terms_content_intro: 'ברוכים הבאים לאפליקציית הקארפול של קהילת יקנעם-בנימינה.',
        internet_law_13: 'חוק שירותי תחבורה (סעיף 13)',
        terms_law_note: 'שימוש באפליקציה זו מיועד לשיתוף נסיעות ללא מטרת רווח מסחרי.',
        terms_close: 'הבנתי, תודה',
        navigate_waze: 'ניווט ב-Waze',
        navigate_google: 'ניווט ב-Google Maps',
        share_trip: 'שיתוף',
        share_message_offer: 'היי! אני יוצא בנסיעה {direction} בשעה {time} בתאריך {date}. הצטרפו אליי כאן: {link}',
        share_message_request: 'היי! אני מחפש נסיעה {direction} בשעה {time} בתאריך {date}. מישהו בדרך? {link}',
        leave_ride_modal_title: 'עזיבת נסיעה',
        leave_ride_modal_confirm_msg: 'האם אתם בטוחים שברצונכם לעזוב את הנסיעה?',
        remove_passenger_modal_content: 'האם להסיר את {name} מהנסיעה?',
        remove_passenger_confirm_button: 'כן, הסר נוסע',
        notif_join_msg: '{name} ביקש/ה להצטרף לנסיעה שלך',
        notif_approved_title: 'בקשתך אושרה!',
        notif_approved_msg: 'הנהג אישר את הצטרפותך לנסיעה. פרטי הקשר זמינים כעת.',
        notif_invite_title: 'קיבלת הצעה לנסיעה!',
        notif_invite_msg: '{name} הזמין אותך לנסיעה {direction} בשעה {time}',
        notif_rejected_title: 'בקשת ההצטרפות נדחתה',
        notif_rejected_msg: 'מצטערים, אך לא ניתן לצרף אותך לנסיעה זו כרגע.',
        notif_trip_cancelled_title: 'נסיעה בוטלה',
        notif_trip_cancelled_msg: 'נסיעה שהיית רשום/ה אליה בוטלה על ידי הנהג.',
        match_found_title: 'נמצאה התאמה!',
        match_found_desc: 'מישהו פרסם נסיעה שתואמת את הבקשה שלך!',
        filter_all: 'הכל',
        filter_departure_time: 'שעת יציאה',
        filter_pickup_time: 'שעת איסוף',
        ride_count_single: 'נסיעה אחת',
        ride_count_plural: '{count} נסיעות',
        request_count_single: 'בקשה אחת',
        request_count_plural: '{count} בקשות',
        sort_time_asc: 'שעה (עולה)',
        sort_time_desc: 'שעה (יורד)',
        community: 'קהילה',
        notif_request_title: 'בקשת הצטרפות',
        driver_label: 'נהג/ת',
        passenger_label: 'נוסע/ת',
        chat_header_status: '1 {driver}, {count} נוסעים',
        seats_full_label_offer: 'מקומות שנותרו',
        seats_full_label_request: 'מקומות דרושים',
        notif_passenger_left_title: 'נוסע עזב את הנסיעה',
        notif_passenger_left_msg: '{name} עזב/ה את הנסיעה שלך',
        
        v_title: 'ציר זמן והיסטוריית גרסאות',
        v_desc: 'כל העדכונים והשיפורים מאז הקמת האפליקציה',
        v_initial: 'הקמת האפליקציה: גרסה ראשונית לקהילת יקנעם-בנימינה, רישום ופרסום נסיעות בסיסי.',
        v_chat: 'מערכת צ׳אט: הוספת צ׳אט קבוצתי לכל נסיעה לתיאום איסוף בזמן אמת.',
        v_pwa: 'תמיכה ב-PWA: אפשרות להתקנה על מסך הבית ושיפור מהירות הטעינה.',
        v_notif: 'התראות Push: מערכת התראות חכמה על אישורי נסיעה, בקשות חדשות וצ׳אטים.',
        v_admin: 'מרכז ניהול: הקמת דשבורד למנהלים, ניהול משתמשים ושידור הודעות גלובליות.',
        v_ui_ux: 'שדרוג עיצוב: מעבר לעיצוב מודרני, תמיכה מלאה במצב כהה והנחיות התקנה מפורטות.',
        pickup_modal_title: 'מאיפה לאסוף?',
        pickup_modal_desc: 'כדי שהנהג ידע איפה לחכות לך, אנא הזן נקודת איסוף מדויקת.',
        pickup_modal_placeholder: 'למשל: ליד הצומת, בתחנת האוטובוס...',
        pickup_modal_btn: 'שלח בקשת הצטרפות',
        offer_to_join: 'הצע להצטרף לנסיעה',
        invite_to_ride: 'הזמנה לנסיעה',
        select_trip_to_invite: 'בחרו אחת מהנסיעות שלכם:',
        no_active_rides_to_invite: 'אין לכם נסיעות פעילות להציע',
        passenger_busy_error: 'הנוסע כבר תפוס',
        request_status_title: 'סטטוס הבקשה שלך'
    }
};

export const LocalizationProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('he');
    const [isDarkMode, setIsDarkMode] = useState(false);

    useEffect(() => {
        if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
            setIsDarkMode(true);
        }
    }, []);

    useEffect(() => {
        if (isDarkMode) document.documentElement.classList.add('dark');
        else document.documentElement.classList.remove('dark');
    }, [isDarkMode]);

    const toggleLanguage = useCallback(() => setLanguage(prev => (prev === 'en' ? 'he' : 'en')), []);
    const toggleTheme = useCallback(() => setIsDarkMode(prev => !prev), []);

    const value = useMemo(() => {
        const dir: Direction = language === 'he' ? 'rtl' : 'ltr';
        const t = (key: string) => translations[language][key] || key;
        return { language, dir, t, toggleLanguage, isDarkMode, toggleTheme };
    }, [language, isDarkMode]);

    return (
        <LocalizationContext.Provider value={value}>
            {children}
        </LocalizationContext.Provider>
    );
};

export const useLocalization = () => {
    const context = useContext(LocalizationContext);
    if (context === undefined) throw new Error('useLocalization error');
    return context;
};
