
import React, { createContext, useState, useContext, useMemo, useCallback, useEffect, ReactNode } from 'react';
import { Translations } from '../types';

type Language = 'en' | 'he';
type Direction = 'ltr' | 'rtl';

interface LocalizationContextType {
    language: Language;
    dir: Direction;
    t: (key: string) => string;
    toggleLanguage: () => void;
    isDarkMode: boolean;
    toggleTheme: () => void;
}

const translations: Translations = {
    en: {
        app_title: 'Yokneam-Binyamina Carpool',
        yokneam_to_binyamina: 'Yokneam to Binyamina',
        binyamina_to_yokneam: 'Binyamina to Yokneam',
        city_yokneam: 'Yokneam',
        city_binyamina: 'Binyamina',
        logout: 'Logout',
        login_with_google: 'Continue with Google',
        phone_number: 'Phone Number',
        save_profile: 'Save Profile',
        post_a_trip: 'Post Ride',
        departure_time: 'Time',
        departure_date: 'Date',
        available_seats: 'Seats',
        publish_trip: 'Publish Ride',
        publish_request: 'Publish Request',
        join: 'Request to Join',
        join_pending: 'Request Sent',
        join_approved: 'Joined',
        pending_requests: 'Pending Requests',
        approve: 'Approve',
        reject: 'Reject',
        leave_ride: 'Leave Ride',
        leave_ride_confirm: 'Are you sure you want to cancel your spot?',
        leave_ride_modal_title: 'Cancel Spot',
        leave_ride_modal_content: 'Are you sure you want to cancel your spot on this ride? The driver will be notified.',
        seats_left: 'left',
        driver: 'Driver',
        passenger: 'Passenger',
        guest: 'Guest',
        pickup_location: 'Pickup Location',
        departure_point: 'Pickup Point',
        departure_point_offer: 'Departure Point',
        departure_point_request: 'Pickup Point',
        email_address: 'Email Address',
        password: 'Password',
        sign_in: 'Sign In',
        dont_have_account: "Don't have an account?",
        sign_up: 'Sign Up',
        full_name: 'Full Name (Hebrew)',
        full_name_en: 'Full Name (English)',
        create_account: 'Create Account',
        register_subtitle: 'Join the community and start riding together.',
        reset_your_password: 'Reset Password',
        forgot_password_subtitle: "Enter your email and we'll send you a reset link.",
        back_to_login: 'Back to Login',
        login_subtitle: 'Commute smarter, together.',
        remember_me: 'Remember me',
        edit: 'Edit',
        delete: 'Delete',
        cancel_trip_confirm: 'Delete this trip permanently?',
        cancel_request_confirm: 'Cancel this ride request?',
        cancel_request: 'Cancel Request',
        join_confirmation: 'Send request to join this ride?',
        offer_confirmation: 'Offer a ride?',
        call: 'Call',
        whatsapp: 'WhatsApp',
        share_ride: 'Share Ride',
        settings_title: 'Settings',
        about_title: 'About Us',
        menu_home: 'Home',
        menu_schedule: 'Schedule',
        menu_profile: 'Profile',
        menu_settings: 'Settings',
        menu_about: 'About',
        menu_admin: 'Admin Panel',
        trip_type_offer: "I'm Driving",
        trip_type_request: "I Need a Ride",
        recurring_ride: "Recurring Ride",
        day_sun: "Sun", day_mon: "Mon", day_tue: "Tue", day_wed: "Wed", day_thu: "Thu", day_fri: "Fri", day_sat: "Sat",
        no_trips_title: 'No rides yet',
        no_trips_subtitle: 'Be the first to post a ride for this route!',
        no_requests_title: 'No ride requests',
        no_requests_subtitle: 'Be the first to post a ride request for this route!',
        post_request_now: 'Post Request',
        be_the_first: 'Post Now',
        no_trips_schedule: 'No rides scheduled for this day.',
        post_ride_now: 'Post a ride now!',
        day_today: 'Today',
        day_tomorrow: 'Tomorrow',
        day_upcoming: 'Upcoming',
        day_all: 'All',
        tab_offers: 'Drivers',
        tab_requests: 'Passengers',
        stats_rides_given: 'Given',
        stats_trips_taken: 'Taken',
        history_title: 'History',
        history_tab_driver: 'As Driver',
        history_tab_passenger: 'As Passenger',
        history_empty: 'No history found.',
        profile_edit: 'Edit Profile',
        profile_save: 'Save',
        profile_cancel: 'Cancel',
        forgot_password: 'Forgot Password?',
        already_have_account: 'Already have an account?',
        error_generic: 'Something went wrong.',
        error_location_required: 'Pickup location is required.',
        error_seats_limit: 'Cannot set seats lower than currently approved passengers.',
        pickup_placeholder_driver: 'Select or type location',
        pickup_placeholder_passenger: 'Where to pick you up?',
        notifications_title: 'Notifications',
        mark_all_read: 'Read all',
        no_notifications: 'No notifications',
        contact_via_whatsapp: 'Contact Support',
        about_mission_title: 'Our Mission',
        about_mission_desc: 'Connecting Yokneam & Binyamina for a greener commute.',
        about_safety_title: 'Safety First',
        about_safety_desc: 'Community verified by phone numbers.',
        community_guidelines: 'Community Guidelines',
        guideline_1: 'Be punctual',
        guideline_2: 'Be respectful',
        guideline_3: 'Communicate',
        about_contact_title: 'Support',
        about_contact_desc: 'We are here to help.',
        settings_notifications: 'Notifications',
        settings_notifications_desc: 'Trip alerts',
        settings_privacy: 'Privacy',
        settings_theme: 'Dark Mode',
        settings_language: 'Language',
        reset_success: 'Reset link sent!',
        send_reset_link: 'Send Link',
        seats_needed: 'Seats needed',
        save_changes: 'Save Changes',
        hero_title: 'Yokneam-Binyamina Carpool',
        hero_subtitle: 'The efficient, friendly, and green way to commute between Yokneam and Binyamina.',
        hero_extra: 'Community • Green • Fast',
        select_time: 'Select Time',
        select_date: 'Select Date',
        confirm: 'Confirm',
        hour: 'Hour',
        minute: 'Minute',
        day: 'Day',
        month: 'Month',
        year: 'Year',
        filter_departure_time: 'Filter by departure time',
        filter_pickup_time: 'Filter by pickup time',
        complete_profile: 'Complete Your Profile',
        trip_full: 'Ride Full',
        passengers_title: 'Passengers',
        join_success: 'You joined the ride!',
        notif_request_title: 'New Request',
        notif_request_msg: 'Someone requested to join your ride.',
        notif_join_msg: '{name} requested to join your ride.',
        notif_approved_title: 'Request Approved',
        notif_approved_msg: 'The driver approved your request!',
        notif_rejected_title: 'Request Declined',
        notif_rejected_msg: 'The driver declined your request to join the ride.',
        close_ride: 'Close Ride',
        open_ride: 'Open Ride',
        ride_closed: 'Ride Closed',
        remove_passenger: 'Remove Passenger',
        remove_passenger_confirm: 'Are you sure you want to remove this passenger?',
        remove_passenger_modal_title: 'Remove Passenger',
        remove_passenger_modal_content: 'Are you sure you want to remove {name} from the ride?',
        remove_passenger_confirm_button: 'Remove',
        delete_all: 'Delete All',
        notif_removed_title: 'Removed from Ride',
        notif_removed_msg: 'The driver removed you from the ride.',
        notif_trip_cancelled_title: 'Ride Cancelled',
        notif_trip_cancelled_msg: 'The driver cancelled this ride. Please find an alternative.',
        notif_passenger_left_title: 'Passenger Left',
        notif_passenger_left_msg: '{name} left your ride.',
        notif_trip_updated_title: 'Ride Updated',
        notif_trip_updated_msg: 'The driver updated the ride details (time or pickup point).',
        
        invite_to_ride: 'Invite to Ride',
        invite_sent: 'Invitation Sent',
        cancel_invite: 'Cancel Invitation',
        no_active_rides_to_invite: 'You have no upcoming rides in this direction.',
        notif_invite_title: 'Ride Invitation',
        notif_invite_msg: '{name} invited you to a ride {direction} at {time}.',
        notif_invite_msg_today: '{name} invited you to a ride TODAY {direction} at {time}.',
        notif_invite_msg_tomorrow: '{name} invited you to a ride TOMORROW {direction} at {time}.',
        notif_invite_msg_future: '{name} invited you to a ride on {dayName} {date} {direction} at {time}.',
        notif_invite_accepted_title: 'Invitation Accepted',
        notif_invite_accepted_msg: '{name} accepted your invitation!',
        notif_invite_rejected_title: 'Invitation Declined',
        notif_invite_rejected_msg: '{name} declined your invitation.',
        select_trip_to_invite: 'Select ride to invite them to',
        passenger_busy_error: 'Passenger is already assigned to another ride.',
        request_fulfilled: 'You already joined a ride!',
        passenger_already_assigned: 'Passenger already assigned to a ride.',
        navigate_waze: 'Navigate with Waze',

        error_missing_fields: 'Please fill in all fields.',
        error_user_not_found: 'User not found.',
        error_wrong_password: 'Incorrect password.',
        error_invalid_credential: 'Username or password incorrect.',
        or_continue_with: 'Or continue with',

        ride_count_single: '1 ride',
        ride_count_plural: '{count} rides',
        request_count_single: '1 ride request',
        request_count_plural: '{count} requests',

        share_message_request: "Request: {driver}\n{direction}\n{date} | {time}\nPickup: {location}\nSeats needed: {seats}\n\nLink: {link}",
        share_message_offer: "Driver: {driver}\n{direction}\n{date} | {time}\nPickup: {location}\nSeats: {seats}\n\nLink: {link}",
        
        error_404_title: "Oops! Off the map?",
        error_404_subtitle: "The road you are looking for seems to lead nowhere.",
        back_home: "Back on Track (Home)",

        select_common_location: 'Select common location...',
        loc_train_binyamina: 'Binyamina Train Station',
        loc_big_yokneam: 'BIG Center Yokneam',
        loc_g_center: 'G Center Yokneam',
        loc_hitech_park: 'High-Tech Park Yokneam',
        loc_megiddo_junction: 'Megiddo Junction',
        loc_elyst_junction: 'Elyakim Junction',
        loc_custom: 'Custom Location (Type below)',
        loc_binyamina_carpool: 'Carpool Parking (Binyamina)',
        loc_binyamina_ind: 'Industrial Zone (Binyamina)',

        sort_newest: 'Newest',
        sort_oldest: 'Oldest',
        sort_time_asc: 'Time (Asc)',
        sort_time_desc: 'Time (Desc)',
        filter_all: 'All',
        filter_direction_all: 'All Directions',

        // About Page New Translations
        about_how_it_works: 'How it Works',
        about_step_1_title: 'Sign Up',
        about_step_1_desc: 'Create a profile with your phone number to start.',
        about_step_2_title: 'Find or Post',
        about_step_2_desc: 'Offer a ride or search for one matching your schedule.',
        about_step_3_title: 'Ride Together',
        about_step_3_desc: 'Connect via WhatsApp, navigate, and save money.',
        about_stats_title: 'Community Impact',
        stat_members: 'Members',
        stat_rides: 'Rides Shared',
        stat_co2: 'CO2 Saved',
        about_why_us: 'Why Join?',
        why_1_title: 'Save Money',
        why_1_desc: 'Share fuel costs and save on daily commute expenses.',
        why_2_title: 'Eco Friendly',
        why_2_desc: 'Reduce cars on the road and lower your carbon footprint.',
        why_3_title: 'Community',
        why_3_desc: 'Meet your neighbors and make commuting fun.',

        // Admin
        admin_panel: 'Admin Panel',
        admin_subtitle: 'System Management',
        access_denied: 'Access Denied',
        admin_tab_stats: 'Dashboard',
        admin_tab_users: 'Users',
        admin_tab_trips: 'Trips',
        admin_tab_changelog: 'Changelog',
        admin_tab_broadcast: 'Broadcast',
        admin_tab_reports: 'Reports',
        stat_total_users: 'Total Users',
        stat_admins: 'Admins',
        system_status: 'System Status',
        search_users: 'Search users...',
        make_admin: 'Make Admin',
        demote_admin: 'Revoke Admin',
        delete_user_confirm: 'Delete User?',
        send_broadcast: 'Send Global Broadcast',
        broadcast_desc: 'Send a notification to all registered users.',
        broadcast_placeholder: 'Type your message here...',
        send_now: 'Send Now',
        broadcast_sent: 'Broadcast sent successfully!',
        confirm_promote: 'Are you sure you want to promote this user to Admin?',
        confirm_demote: 'Are you sure you want to revoke Admin rights?',
        confirm_broadcast: 'Are you sure you want to send this message to ALL users?',
        admin_update_title: 'System Update',
        changelog_title: 'App Version History',
        changelog_desc: 'Track the evolution of the application.',
        trip_inspector_title: 'Trip Inspector',
        trip_inspector_desc: 'View and manage all active and past trips.',
        confirm_delete_trip_admin: 'Admin: Force delete this trip?',
        feature_new: 'New',
        feature_fix: 'Fix',
        feature_ui: 'UI',
        stat_active_trips: 'Active Trips',
        stat_total_trips: 'Total Trips',
        stat_trip_distribution: 'Trip Distribution',
        stat_system_health: 'System Health',
        
        stat_db_status: 'Database Status',
        stat_auth_status: 'Auth Service',
        stat_storage: 'Storage Usage',
        status_online: 'Online',
        status_operational: 'Operational',

        // Admin Trip Filters
        filter_status_all: 'All Status',
        filter_status_active: 'Active',
        filter_status_closed: 'Closed',
        filter_status_full: 'Full',
        filter_type_all: 'All Types',

        // Report System
        report_issue: 'Help & Feedback',
        report_modal_title: 'Feedback & Support',
        report_type_bug: 'Bug Report',
        report_type_improvement: 'Suggestion',
        report_desc_placeholder: 'Describe the issue or suggestion...',
        report_submit: 'Submit Report',
        report_submitted: 'Thank you! Your report has been sent.',
        notif_new_report_title: 'New System Report',
        notif_new_report_msg: 'A user submitted a new bug report or suggestion.',
        notif_report_resolved_title: 'Report Resolved',
        notif_report_resolved_msg: 'Your feedback has been addressed by the team. Thank you!',
        filter_user_role_all: 'All Roles',
        filter_user_role_admin: 'Admins',
        filter_user_role_user: 'Users',
        filter_user_sort_newest: 'Newest',
        filter_user_sort_oldest: 'Oldest',
        report_status_open: 'Open',
        report_status_resolved: 'Resolved',
        resolve: 'Resolve',
        promote: 'Promote',
        demote: 'Demote',
        delete_report: 'Delete Report',
        delete_report_confirm: 'Delete this report?',
        no_reports: 'No reports found.',

        // Badges & Chat
        badge_newcomer: 'Newcomer',
        badge_frequent_flyer: 'Frequent Flyer',
        badge_driver_pro: 'Driver Pro',
        badge_community_legend: 'Community Legend',
        chat_title: 'Ride Chat',
        chat_placeholder: 'Type a message...',
        chat_open: 'Chat',
        no_messages: 'No messages yet. Start the conversation!',
        you: 'You',
        driver_label: 'Driver',
        is_typing: '{name} is typing...',
        is_typing_plural: '{count} people are typing...',

        // New Error Messages for Stale Notifications
        error_request_expired: 'This request is no longer valid (passenger may have canceled).',
        error_invite_expired: 'This ride is no longer available or full.',
        error_passenger_already_approved: 'Passenger already approved. Notification cleared.',
        error_already_joined: 'You have already joined this ride!',
        error_already_in_trip: 'User is already in this ride. Notification cleared.',
        error_remove_self_admin: 'You cannot remove admin rights from yourself.',

        // Car Details & Terms
        my_car_title: 'My Car',
        car_model: 'Car Model',
        car_color: 'Color',
        car_plate: 'License Plate',
        car_model_placeholder: 'e.g. Kia Picanto',
        car_color_placeholder: 'e.g. White',
        car_plate_placeholder: '12-345-67',
        terms_title: 'Terms of Use & Privacy',
        terms_close: 'Close',
        internet_law_13: 'Spam Law (Amendment 40 to Communications Law)',
        terms_content_intro: 'By using this app, you agree to the following terms...',
        terms_law_note: 'Notifications sent by this app are service messages related to your rides and are compliant with Israeli Law.',
        match_found_title: 'Ride Found!',
        match_found_desc: 'A new ride matching your request was just posted.',
    },
    he: {
        app_title: 'קארפול יקנעם-בנימינה',
        yokneam_to_binyamina: 'יקנעם לבנימינה',
        binyamina_to_yokneam: 'בנימינה ליקנעם',
        city_yokneam: 'יקנעם',
        city_binyamina: 'בנימינה',
        logout: 'התנתקות',
        login_with_google: 'המשך עם Google',
        phone_number: 'מספר נייד',
        save_profile: 'שמור פרופיל',
        post_a_trip: 'פרסם נסיעה',
        departure_time: 'שעה',
        departure_date: 'תאריך',
        available_seats: 'מושבים',
        publish_trip: 'פרסום נסיעה',
        publish_request: 'פרסום בקשה',
        join: 'בקש להצטרף',
        join_pending: 'בקשה נשלחה',
        join_approved: 'אושר',
        pending_requests: 'בקשות ממתינות',
        approve: 'אשר',
        reject: 'דחה',
        leave_ride: 'ביטול הצטרפות',
        leave_ride_confirm: 'האם את/ה בטוח/ה שברצונך לבטל?',
        leave_ride_modal_title: 'ביטול הצטרפות',
        leave_ride_modal_content: 'האם את/ה בטוח/ה שברצונך לבטל את ההצטרפות לנסיעה? הנהג יקבל על כך עדכון.',
        seats_left: 'נותרו',
        driver: 'נהג/ת',
        passenger: 'נוסע/ת',
        guest: 'אורח',
        pickup_location: 'איסוף',
        departure_point: 'נקודת איסוף',
        departure_point_offer: 'נקודת יציאה',
        departure_point_request: 'נקודת איסוף',
        email_address: 'אימייל',
        password: 'סיסמה',
        sign_in: 'כניסה',
        dont_have_account: 'עדיין אין לך חשבון?',
        sign_up: 'הרשמה',
        full_name: 'שם מלא (עברית)',
        full_name_en: 'שם מלא (אנגלית)',
        create_account: 'יצירת חשבון',
        register_subtitle: 'הצטרפו לקהילה ותתחילו לנסוע יחד.',
        reset_your_password: 'איפוס סיסמה',
        forgot_password_subtitle: 'הזינו את המייל שלכם ונשלח לכם קישור לאיפוס סיסמה.',
        back_to_login: 'חזרה לכניסה',
        login_subtitle: 'נוסעים חכם, נוסעים יחד.',
        remember_me: 'זכור אותי',
        edit: 'עריכה',
        delete: 'מחיקה',
        cancel_trip_confirm: 'למחוק את הנסיעה לצמיתות?',
        cancel_request_confirm: 'לבטל את בקשת הטרמפ?',
        cancel_request: 'ביטול בקשה',
        join_confirmation: 'לשלוח בקשת הצטרפות?',
        offer_confirmation: 'להציע את הטרמפ?',
        call: 'חיוג',
        whatsapp: 'וואטסאפ',
        share_ride: 'שיתוף נסיעה',
        settings_title: 'הגדרות',
        about_title: 'קארפול יקנעם בנימינה',
        menu_home: 'ראשי',
        menu_schedule: 'לו"ז שבועי',
        menu_profile: 'פרופיל',
        menu_settings: 'הגדרות',
        menu_about: 'אודות',
        menu_admin: 'ניהול מערכת',
        trip_type_offer: "אני נוהג/ת",
        trip_type_request: "צריך/ה טרמפ",
        recurring_ride: "נסיעה קבועה",
        day_sun: "א׳", day_mon: "ב׳", day_tue: "ג׳", day_wed: "ד׳", day_thu: "ה׳", day_fri: "ו׳", day_sat: "ש׳",
        no_trips_title: 'אין נסיעות כרגע',
        no_trips_subtitle: 'היו הראשונים לפרסם נסיעה במסלול זה!',
        no_requests_title: 'אין בקשות נסיעה',
        no_requests_subtitle: 'היו הראשונים לפרסם בקשת נסיעה!',
        post_request_now: 'פרסם בקשה',
        be_the_first: 'פרסם נסיעה',
        no_trips_schedule: 'אין נסיעות ליום זה.',
        post_ride_now: 'פרסמו נסיעה!',
        day_today: 'היום',
        day_tomorrow: 'מחר',
        day_upcoming: 'בהמשך',
        day_all: 'הכל',
        tab_offers: 'נהגים',
        tab_requests: 'נוסעים',
        stats_rides_given: 'נסיעות כנהג',
        stats_trips_taken: 'נסיעות כנוסע',
        history_title: 'היסטוריה',
        history_tab_driver: 'כנהג/ת',
        history_tab_passenger: 'כנוסע/ת',
        history_empty: 'אין עדיין היסטוריה.',
        profile_edit: 'עריכה',
        profile_save: 'שמירה',
        profile_cancel: 'ביטול',
        forgot_password: 'שכחת סיסמה?',
        already_have_account: 'כבר רשום?',
        error_generic: 'שגיאה כללית.',
        error_location_required: 'חובה להזין נקודת איסוף.',
        error_seats_limit: 'לא ניתן להגדיר פחות מושבים מכמות הנוסעים המאושרים.',
        pickup_placeholder_driver: 'בחר או הקלד מיקום',
        pickup_placeholder_passenger: 'מאיפה לאסוף אותך?',
        notifications_title: 'התראות',
        mark_all_read: 'קרא הכל',
        no_notifications: 'אין התראות',
        contact_via_whatsapp: 'תמיכה בוואטסאפ',
        about_mission_title: 'המטרה שלנו',
        about_mission_desc: 'חיבור תושבי יקנעם ובנימינה לנסיעה משותפת וירוקה.',
        about_safety_title: 'בטיחות מעל הכל',
        about_safety_desc: 'קהילה מאומתת טלפונית.',
        community_guidelines: 'כללי הקהילה',
        guideline_1: 'דיוק בזמנים',
        guideline_2: 'כבוד הדדי',
        guideline_3: 'תקשורת טובה',
        about_contact_title: 'תמיכה ויצירת קשר',
        about_contact_desc: 'אנחנו כאן לכל שאלה.',
        settings_notifications: 'התראות',
        settings_notifications_desc: 'עדכונים על נסיעות',
        settings_privacy: 'פרטיות',
        settings_theme: 'מצב כהה',
        settings_language: 'שפה',
        reset_success: 'נשלח קישור לאיפוס!',
        send_reset_link: 'שלח קישור',
        seats_needed: 'מושבים',
        save_changes: 'שמור שינויים',
        hero_title: 'קארפול יקנעם-בנימינה',
        hero_subtitle: 'הדרך היעילה, החברתית והירוקה להגיע לעבודה ולבית.',
        hero_extra: 'קהילה • ירוק • מהיר',
        select_time: 'בחירת שעה',
        select_date: 'בחירת תאריך',
        confirm: 'אישור',
        hour: 'שעה',
        minute: 'דקה',
        day: 'יום',
        month: 'חודש',
        year: ' שנה',
        filter_departure_time: 'סינון לפי שעת יציאה',
        filter_pickup_time: 'סינון לפי שעת איסוף',
        complete_profile: 'השלמת פרופיל',
        trip_full: 'נסיעה מלאה',
        passengers_title: 'נוסעים',
        join_success: 'הצטרפת לנסיעה בהצלחה!',
        notif_request_title: 'בקשת הצטרפות',
        notif_request_msg: 'נוסע ביקש להצטרף לנסיעה שלך.',
        notif_join_msg: '{name} ביקש להצטרף לנסיעה שלך.',
        notif_approved_title: 'בקשה אושרה',
        notif_approved_msg: 'הנהג אישר את הצטרפותך לנסיעה!',
        notif_rejected_title: 'בקשה נדחתה',
        notif_rejected_msg: 'הנהג דחה את בקשת ההצטרפות שלך לנסיעה.',
        close_ride: 'סגור הצטרפות',
        open_ride: 'פתח הצטרפות',
        ride_closed: 'הנסיעה נסגרה',
        remove_passenger: 'הסר נוסע',
        remove_passenger_confirm: 'האם להסיר את הנוסע מהנסיעה?',
        remove_passenger_modal_title: 'הסרת נוסע',
        remove_passenger_modal_content: 'האם להסיר את {name} מהנסיעה?',
        remove_passenger_confirm_button: 'הסר',
        delete_all: 'נקה הכל',
        notif_removed_title: 'הוסרת מהנסיעה',
        notif_removed_msg: 'הנהג הסיר אותך מהנסיעה.',
        notif_trip_cancelled_title: 'הנסיעה בוטלה',
        notif_trip_cancelled_msg: 'הנהג ביטל את הנסיעה. יש למצוא נסיעה חלופית.',
        notif_passenger_left_title: 'נוסע עזב',
        notif_passenger_left_msg: '{name} עזב/ה את הנסיעה.',
        notif_trip_updated_title: 'הנסיעה עודכנה',
        notif_trip_updated_msg: 'הנהג עדכן את פרטי הנסיעה (שעה או נקודת איסוף).',
        
        invite_to_ride: 'הזמן לנסיעה',
        invite_sent: 'ההזמנה נשלחה',
        cancel_invite: 'ביטול הזמנה',
        no_active_rides_to_invite: 'אין לך נסיעות עתידיות מתאימות להזמנה.',
        notif_invite_title: 'הזמנה לנסיעה',
        notif_invite_msg: '{name} הזמין אותך לנסיעה {direction} בשעה {time}.',
        notif_invite_msg_today: '{name} הזמין אותך לנסיעה היום {direction} בשעה {time}.',
        notif_invite_msg_tomorrow: '{name} הזמין אותך לנסיעה מחר {direction} בשעה {time}.',
        notif_invite_msg_future: '{name} הזמין אותך לנסיעה ביום {dayName} ה-{date} {direction} בשעה {time}.',
        notif_invite_accepted_title: 'ההזמנה התקבלה',
        notif_invite_accepted_msg: '{name} אישר/ה את ההזמנה שלך!',
        notif_invite_rejected_title: 'ההזמנה נדחתה',
        notif_invite_rejected_msg: '{name} דחה/תה את ההזמנה שלך.',
        select_trip_to_invite: 'בחר נסיעה להזמין אליה',
        passenger_busy_error: 'הנוסע כבר משויך לנסיעה אחרת.',
        request_fulfilled: 'כבר שובצת לנסיעה!',
        passenger_already_assigned: 'הנוסע כבר שובץ לנסיעה.',
        navigate_waze: 'נווט עם Waze',

        error_missing_fields: 'יש למלא את כל השדות.',
        error_user_not_found: 'משתמש לא נמצא.',
        error_wrong_password: 'סיסמה שגויה.',
        error_invalid_credential: 'שם משתמש או סיסמה שגויים.',
        or_continue_with: 'או המשך עם',

        ride_count_single: 'נסיעה אחת',
        ride_count_plural: '{count} נסיעות',
        request_count_single: 'בקשת נסיעה אחת',
        request_count_plural: '{count} בקשות',

        share_message_request: "בקשה: {driver}\n{direction}\n{date} | {time}\nאיסוף: {location}\nמושבים: {seats}\n\nלינק: {link}",
        share_message_offer: "נהג/ת: {driver}\n{direction}\n{date} | {time}\nאיסוף: {location}\nמושבים: {seats}\n\nלינק: {link}",

        error_404_title: "אופס! ירדנו מהמסלול",
        error_404_subtitle: "נראה שהדף שחיפשת נסע לכיוון אחר או שלא היה קיים מעולם.",
        back_home: "חזרה למסלול (דף הבית)",

        select_common_location: 'בחר מיקום נפוץ...',
        loc_train_binyamina: 'רכבת בנימינה',
        loc_big_yokneam: 'ביג יקנעם',
        loc_g_center: 'קניון G יקנעם',
        loc_hitech_park: 'פארק הייטק יקנעם',
        loc_megiddo_junction: 'צומת מגידו',
        loc_elyst_junction: 'צומת אליקים',
        loc_custom: 'מיקום אחר (הקלד למטה)',
        loc_binyamina_carpool: 'חניון קארפול (בנימינה)',
        loc_binyamina_ind: 'אזור תעשייה (בנימינה)',

        sort_newest: 'הכי חדש',
        sort_oldest: 'הכי ישן',
        sort_time_asc: 'שעה (עולה)',
        sort_time_desc: 'שעה (יורד)',
        filter_all: 'הכל',
        filter_direction_all: 'כל הכיוונים',

        // About Page New Translations
        about_how_it_works: 'איך זה עובד?',
        about_step_1_title: 'הרשמה מהירה',
        about_step_1_desc: 'יוצרים פרופיל ומאמתים מספר טלפון ברגע.',
        about_step_2_title: 'מוצאים נסיעה',
        about_step_2_desc: 'מפרסמים נסיעה או מחפשים טרמפ קיים בלו"ז.',
        about_step_3_title: 'נוסעים ביחד',
        about_step_3_desc: 'מתחברים בוואטסאפ, מנווטים וחוסכים בעלויות.',
        about_stats_title: 'השפעה קהילתית',
        stat_members: 'חברי קהילה',
        stat_rides: 'נסיעות משותפות',
        stat_co2: 'ק"ג CO2 שנחסך',
        about_why_us: 'למה להצטרף?',
        why_1_title: 'חיסכון כספי',
        why_1_desc: 'חולקים בהוצאות הדלק וחוסכים מאות שקלים בחודש.',
        why_2_title: 'שמירה על הסביבה',
        why_2_desc: 'מורידים את כמות הרכבים בכביש ומפחיתים זיהום.',
        why_3_title: 'קהילה מקומית',
        why_3_desc: 'מכירים את השכנים והופכים את הנסיעה לחוויה.',

        // Admin
        admin_panel: 'ניהול מערכת',
        admin_subtitle: 'אזור למנהלים בלבד',
        access_denied: 'אין גישה',
        admin_tab_stats: 'דשבורד',
        admin_tab_users: 'משתמשים',
        admin_tab_trips: 'נסיעות',
        admin_tab_changelog: 'גרסאות',
        admin_tab_broadcast: 'הודעות',
        admin_tab_reports: 'דיווחים',
        stat_total_users: 'סה"כ משתמשים',
        stat_admins: 'מנהלים',
        system_status: 'סטטוס מערכת',
        search_users: 'חיפוש משתמש...',
        make_admin: 'מנה למנהל',
        demote_admin: 'הסר ניהול',
        delete_user_confirm: 'למחוק משתמש?',
        send_broadcast: 'שלח הודעה לכולם',
        broadcast_desc: 'שליחת התראה לכל המשתמשים הרשומים באפליקציה.',
        broadcast_placeholder: 'כתוב את ההודעה כאן...',
        send_now: 'שלח עכשיו',
        broadcast_sent: 'ההודעה נשלחה בהצלחה!',
        confirm_promote: 'האם למנות משתמש זה למנהל?',
        confirm_demote: 'האם להסיר הרשאות ניהול?',
        confirm_broadcast: 'האם לשלוח את ההודעה לכל המשתמשים?',
        admin_update_title: 'עדכון מערכת',
        changelog_title: 'היסטוריית גרסאות',
        changelog_desc: 'מעקב אחר התפתחות האפליקציה, פיצ׳רים ותיקונים.',
        trip_inspector_title: 'מפקח נסיעות',
        trip_inspector_desc: 'צפייה וניהול של כל הנסיעות במערכת (עתידיות ועבר קרוב).',
        confirm_delete_trip_admin: 'אדמין: למחוק את הנסיעה הזו?',
        feature_new: 'חדש',
        feature_fix: 'תיקון',
        feature_ui: 'עיצוב',
        stat_active_trips: 'נסיעות פעילות',
        stat_total_trips: 'סה"כ נסיעות',
        stat_trip_distribution: 'התפלגות נסיעות',
        stat_system_health: 'בריאות מערכת',
        
        stat_db_status: 'סטטוס מסד נתונים',
        stat_auth_status: 'שירות אימות',
        stat_storage: 'ניצול אחסון',
        status_online: 'מחובר',
        status_operational: 'תקין',

        // Admin Trip Filters
        filter_status_all: 'כל הסטטוסים',
        filter_status_active: 'פעיל',
        filter_status_closed: 'סגור',
        filter_status_full: 'מלא',
        filter_type_all: 'כל הסוגים',

        // Report System
        report_issue: 'עזרה ומשוב',
        report_modal_title: 'משוב ותמיכה',
        report_type_bug: 'דיווח על תקלה',
        report_type_improvement: 'הצעה לשיפור',
        report_desc_placeholder: 'תאר את התקלה או ההצעה לשיפור...',
        report_submit: 'שלח דיווח',
        report_submitted: 'תודה! הדיווח נשלח בהצלחה.',
        notif_new_report_title: 'דיווח מערכת חדש',
        notif_new_report_msg: 'משתמש שלח דיווח על תקלה או הצעה לשיפור.',
        notif_report_resolved_title: 'הדיווח טופל',
        notif_report_resolved_msg: 'המשוב שלך טופל על ידי הצוות. תודה רבה!',
        filter_user_role_all: 'כל התפקידים',
        filter_user_role_admin: 'מנהלים',
        filter_user_role_user: 'משתמשים',
        filter_user_sort_newest: 'הכי חדש',
        filter_user_sort_oldest: 'הכי ישן',
        report_status_open: 'פתוח',
        report_status_resolved: 'טופל',
        resolve: 'סמן כטופל',
        promote: 'מנה למנהל',
        demote: 'הסר ניהול',
        delete_report: 'מחק דיווח',
        delete_report_confirm: 'האם למחוק את הדיווח?',
        no_reports: 'אין דיווחים.',

        // Badges & Chat
        badge_newcomer: 'חדש/ה',
        badge_frequent_flyer: 'נוסע/ת מתמיד/ה',
        badge_driver_pro: 'נהג/ת מקצוען',
        badge_community_legend: 'אגדת קהילה',
        chat_title: 'צ׳אט נסיעה',
        chat_placeholder: 'הקלד הודעה...',
        chat_open: 'צ׳אט',
        no_messages: 'אין הודעות עדיין. תתחילו לדבר!',
        you: 'אני',
        driver_label: 'נהג/ת',
        is_typing: '{name} מקליד/ה...',
        is_typing_plural: '{count} אנשים מקלידים...',

        // New Error Messages for Stale Notifications
        error_request_expired: 'הבקשה אינה בתוקף (ייתכן והנוסע ביטל).',
        error_invite_expired: 'הנסיעה התמלאה או שאינה זמינה יותר.',
        error_passenger_already_approved: 'הנוסע כבר אושר לנסיעה.',
        error_already_joined: 'כבר הצטרפת לנסיעה זו!',
        error_already_in_trip: 'הנוסע כבר בנסיעה זו. ההתראה נוקתה.',
        error_remove_self_admin: 'לא ניתן להסיר הרשאות ניהול מעצמך.',

        // Car Details & Terms
        my_car_title: 'פרטי הרכב שלי',
        car_model: 'דגם רכב',
        car_color: 'צבע',
        car_plate: 'מספר רכב',
        car_model_placeholder: 'לדוגמא: קיה פיקנטו',
        car_color_placeholder: 'לדוגמא: לבן',
        car_plate_placeholder: '12-345-67',
        terms_title: 'תנאי שימוש ופרטיות',
        terms_close: 'סגור',
        internet_law_13: 'חוק הספאם (תיקון 40 לחוק התקשורת)',
        terms_content_intro: 'בעת השימוש באפליקציה, הנך מסכים/ה לתנאים הבאים...',
        terms_law_note: 'ההתראות הנשלחות באפליקציה הינן הודעות שירות הקשורות לנסיעותיך ותואמות את דרישות החוק בישראל.',
        match_found_title: 'נמצאה נסיעה!',
        match_found_desc: 'פורסמה נסיעה חדשה התואמת את בקשתך.',
    },
};

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

export const LocalizationProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('he');
    const [isDarkMode, setIsDarkMode] = useState(false);

    useEffect(() => {
        if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
            setIsDarkMode(true);
        }
    }, []);

    useEffect(() => {
        if (isDarkMode) {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark');
        }
    }, [isDarkMode]);

    const toggleLanguage = useCallback(() => {
        setLanguage(prevLang => (prevLang === 'en' ? 'he' : 'en'));
    }, []);

    const toggleTheme = useCallback(() => {
        setIsDarkMode(prev => !prev);
    }, []);

    const value = useMemo(() => {
        const dir: Direction = language === 'he' ? 'rtl' : 'ltr';
        const t = (key: string) => translations[language][key] || key;
        return { language, dir, t, toggleLanguage, isDarkMode, toggleTheme };
    }, [language, toggleLanguage, isDarkMode, toggleTheme]);

    return (
        <LocalizationContext.Provider value={value}>
            {children}
        </LocalizationContext.Provider>
    );
};

export const useLocalization = () => {
    const context = useContext(LocalizationContext);
    if (context === undefined) {
        throw new Error('useLocalization must be used within a LocalizationProvider');
    }
    return context;
};
